# Generated by Django 4.2.20 on 2025-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile/default_profile.png', upload_to='profile'),
        ),
    ]
