# Generated by Django 4.2.20 on 2025-10-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='isCurrentAddress',
            field=models.BooleanField(default=False),
        ),
    ]
