# Generated by Django 4.2.20 on 2025-10-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraddress_iscurrentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
