# Generated by Django 4.2.20 on 2025-10-05 04:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_useraddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
