# Generated by Django 4.2.20 on 2025-10-08 06:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='MM', unique=True),
        ),
    ]
