# Generated by Django 4.2.20 on 2025-09-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Reject'), ('C', 'Confirm'), ('PP', 'Prepared'), ('BD', 'Being Delivered'), ('D', 'Delivered')], default='P', max_length=5),
        ),
    ]
