// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLyU4ot6pZWlWEWTliKwU0dOxWxmp7BW4',
    appId: '1:911690060554:web:eef95f87a7d0e7b3e1a0f3',
    messagingSenderId: '911690060554',
    projectId: 'fruithub-9c516',
    authDomain: 'fruithub-9c516.firebaseapp.com',
    storageBucket: 'fruithub-9c516.firebasestorage.app',
    measurementId: 'G-XTR3D231C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbnqf2DrbeC0wRkPViwiO90gz-Vp9d3WQ',
    appId: '1:911690060554:android:a2c8fe4fc5989194e1a0f3',
    messagingSenderId: '911690060554',
    projectId: 'fruithub-9c516',
    storageBucket: 'fruithub-9c516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvytAjm1JmSKzts4rbaJo6gKzzU5M56f8',
    appId: '1:911690060554:ios:980b4140b74e79c1e1a0f3',
    messagingSenderId: '911690060554',
    projectId: 'fruithub-9c516',
    storageBucket: 'fruithub-9c516.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );
}
