# Generated by Django 4.2.20 on 2025-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='menu',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('hottest', 'Hottest'), ('popular', 'Popular'), ('new', 'New')], max_length=20, null=True),
        ),
    ]
