# Generated by Django 4.2.20 on 2025-09-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_rating_menu_rating_count_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, choices=[('hottest', 'Hottest'), ('popular', 'Popular'), ('new', 'New')], max_length=20, null=True),
        ),
    ]
